[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
dim_foreground = "#b0a486"
bright_foreground = "#fae9be"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text = "#ebdbb2"
background = "#665c54"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.dim]
black = "#222222"
red = "#ad1f19"
green = "#818016"
yellow = "#b7821c"
blue = "#3b7174"
magenta = "#965372"
cyan = "#58855a"
white = "#8f8270"

[[colors.indexed_colors]]
index = 16
color = "#d25f1f"

[[colors.indexed_colors]]
index = 17
color = "#ba5f51"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true
title = "Terminal"

[window.padding]
x = 8
y = 8
