[colors.primary]
background = "#feffff"
foreground = "#000000"
dim_foreground = "#3b3b3b"
bright_foreground = "#0f0f0f"

[colors.cursor]
text = "#ffffff"
cursor = "#98989d"

[colors.selection]
text = "#000000"
background = "#abd8ff"

[colors.normal]
black = "#1a1a1a"
red = "#cc372e"
green = "#26a439"
yellow = "#cdac08"
blue = "#0869cb"
magenta = "#9647bf"
cyan = "#479ec2"
white = "#98989d"

[colors.bright]
black = "#1a1a1a"
red = "#cc372e"
green = "#26a439"
yellow = "#cdac08"
blue = "#0869cb"
magenta = "#9647bf"
cyan = "#479ec2"
white = "#98989d"

[colors.dim]
black = "#161616"
red = "#ad2f27"
green = "#208b30"
yellow = "#ae9207"
blue = "#0759ad"
magenta = "#803ca2"
cyan = "#3c86a5"
white = "#818185"

[[colors.indexed_colors]]
index = 16
color = "#cd721b"

[[colors.indexed_colors]]
index = 17
color = "#b26866"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true
title = "Terminal"

[window.padding]
x = 8
y = 8
