[colors.primary]
background = "#f3f4f5"
foreground = "#565e65"
dim_foreground = "#3e454c"
bright_foreground = "#49525B"

[colors.cursor]
text = "#f3f4f5"
cursor = "#3e454c"

[colors.selection]
text = "#565e65"
background = "#d6d8da"

[colors.normal]
black = "#f3f4f5"
red = "#b57e6b"
green = "#6bb57e"
yellow = "#b5b76b"
blue = "#b56bb5"
magenta = "#b56b8c"
cyan = "#6bb5b5"
white = "#565e65"

[colors.bright]
black = "#9aa0a6"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#f3f4f5"

[colors.dim]
black = "#d0d3d6"
red = "#c0a38c"
green = "#8cc0a3"
yellow = "#bcc08c"
blue = "#c08cc0"
magenta = "#c08cac"
cyan = "#8cc0c0"
white = "#a0a8b0"

[[colors.indexed_colors]]
index = 16
color = "#d7943e"

[[colors.indexed_colors]]
index = 17
color = "#d86b91"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true
title = "Terminal"

[window.padding]
x = 8
y = 8
